/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import config.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class CourseForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseForm.class.getName());

    // Menyimpan kode_mk yang sedang dipilih di tabel (untuk UPDATE & DELETE)
    private String selectedKodeMK = null;

    /**
     * Creates new form CourseForm
     */
   public CourseForm() {
        initComponents();
        tampilkanData();

        // Saat baris tabel diklik, isi otomatis ke form
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                isiFormDariTabel();
            }
        });
    }
  /**
     * 
     */
    private void tampilkanData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // kosongkan dulu isi tabel

        String sql = "SELECT kode_mk, nama_mk, sks, semester FROM matakuliah ORDER BY kode_mk";

        try (Connection conn = DBconnection.getConnection();
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {

            int no = 1;
            while (rs.next()) {
                model.addRow(new Object[]{
                    no++,
                    rs.getString("kode_mk"),
                    rs.getString("nama_mk"),
                    rs.getString("sks"),
                    rs.getString("semester")
                });
            }
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * 
     */
    private void isiFormDariTabel() {
        int row = jTable1.getSelectedRow();
        selectedKodeMK = jTable1.getValueAt(row, 1).toString();
        jTextFieldKodeMK.setText(selectedKodeMK);
        jTextFieldNama.setText(jTable1.getValueAt(row, 2).toString());
        jTextFieldSKS.setText(jTable1.getValueAt(row, 3).toString());
        jComboBoxSM.setSelectedItem(jTable1.getValueAt(row, 4).toString());
    }

    /**
     * 
     */
    private void resetForm() {
        jTextFieldKodeMK.setText("");
        jTextFieldNama.setText("");
        jTextFieldSKS.setText("");
        jComboBoxSM.setSelectedIndex(0);
        selectedKodeMK = null;
        jTable1.clearSelection();
    }

    /**
     * 
     */
    private boolean validasiInput() {
        if (jTextFieldKodeMK.getText().trim().isEmpty()
                || jTextFieldNama.getText().trim().isEmpty()
                || jTextFieldSKS.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi!",
                    "Validasi", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            Integer.parseInt(jTextFieldSKS.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "SKS harus berupa angka!",
                    "Validasi", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonUPDATE = new javax.swing.JButton();
        jButtonADD = new javax.swing.JButton();
        jButtonDELETE = new javax.swing.JButton();
        jButtonRESET = new javax.swing.JButton();
        jTextFieldSKS = new javax.swing.JTextField();
        jComboBoxSM = new javax.swing.JComboBox<>();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldKodeMK = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MASTER COURSE");

        jLabel2.setText("Nama mata kuliah");

        jLabel3.setText("Kode Matakuliah");

        jLabel4.setText("SKS");

        jLabel5.setText("Semester");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO", "Kode", "Mata Kuliah", "SKS", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonUPDATE.setText("UPDATE");
        jButtonUPDATE.addActionListener(this::jButtonUPDATEActionPerformed);

        jButtonADD.setText("ADD");
        jButtonADD.addActionListener(this::jButtonADDActionPerformed);

        jButtonDELETE.setText("DELETE");
        jButtonDELETE.addActionListener(this::jButtonDELETEActionPerformed);

        jButtonRESET.setText("RESET");
        jButtonRESET.addActionListener(this::jButtonRESETActionPerformed);

        jTextFieldSKS.setText("jTextField1");

        jComboBoxSM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1", "Semester 2", "Semester 3" }));
        jComboBoxSM.addActionListener(this::jComboBoxSMActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButtonUPDATE)
                        .addGap(186, 186, 186)
                        .addComponent(jButtonDELETE)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonRESET)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonADD)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUPDATE)
                    .addComponent(jButtonADD)
                    .addComponent(jButtonDELETE)
                    .addComponent(jButtonRESET))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
        // TODO add your handling code here:
        if (!validasiInput()) {
            return;
        }

        String kodeMK = jTextFieldKodeMK.getText().trim();
        String nama = jTextFieldNama.getText().trim();
        String sks = jTextFieldSKS.getText().trim();
        String semester = jComboBoxSM.getSelectedItem().toString();

        String sql = "INSERT INTO matakuliah (kode_mk, nama_mk, sks, semester) VALUES (?, ?, ?, ?)";

        try (Connection conn = DBconnection.getConnection();
                PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, kodeMK);
            ps.setString(2, nama);
            ps.setString(3, sks);
            ps.setString(4, semester);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan.");
            tampilkanData();
            resetForm();

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Gagal menambah data: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
                                              
    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jComboBoxSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSMActionPerformed
        // TODO add your handling code here:
                                               

    /**
     * @param args the command line arguments
     */
    try{
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
}catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new CourseForm().setVisible(true));

    }//GEN-LAST:event_jComboBoxSMActionPerformed

    private void jButtonUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUPDATEActionPerformed
        // TODO add your handling code here:
        if (selectedKodeMK == null) {
            JOptionPane.showMessageDialog(this, "Pilih dulu data pada tabel yang ingin diupdate.",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validasiInput()) {
            return;
        }

        String nama = jTextFieldNama.getText().trim();
        String sks = jTextFieldSKS.getText().trim();
        String semester = jComboBoxSM.getSelectedItem().toString();

        String sql = "UPDATE matakuliah SET nama_mk = ?, sks = ?, semester = ? WHERE kode_mk = ?";

        try (Connection conn = DBconnection.getConnection();
                PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, nama);
            ps.setString(2, sks);
            ps.setString(3, semester);
            ps.setString(4, selectedKodeMK);
            int affected = ps.executeUpdate();

            if (affected > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate.");
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan.", "Info", JOptionPane.WARNING_MESSAGE);
            }
            tampilkanData();
            resetForm();

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Gagal update data: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
                                                 
    }//GEN-LAST:event_jButtonUPDATEActionPerformed

    private void jButtonDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDELETEActionPerformed
        // TODO add your handling code here:
        if (selectedKodeMK == null) {
            JOptionPane.showMessageDialog(this, "Pilih dulu data pada tabel yang ingin dihapus.",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus data \"" + selectedKodeMK + "\"?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String sql = "DELETE FROM matakuliah WHERE kode_mk = ?";

        try (Connection conn = DBconnection.getConnection();
                PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, selectedKodeMK);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            tampilkanData();
            resetForm();

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
                                                 
    }//GEN-LAST:event_jButtonDELETEActionPerformed

    private void jButtonRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRESETActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_jButtonRESETActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonDELETE;
    private javax.swing.JButton jButtonRESET;
    private javax.swing.JButton jButtonUPDATE;
    private javax.swing.JComboBox<String> jComboBoxSM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldKodeMK;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldSKS;
    // End of variables declaration//GEN-END:variables
}