/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.lecture;
import model.KRS;
import model.Course;
import java.util.ArrayList;
import model.Student;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

public class inputnilai extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(inputnilai.class.getName());

    /**
     * @author User
     */
 
    ArrayList<Student> listMahasiswa = new ArrayList<>();
    ArrayList<Course> listMataKuliah = new ArrayList<>();
    ArrayList<lecture> listLecture = new ArrayList<>();
    final String[] semester = {"1", "2", "3"};
    final DefaultComboBoxModel comboModelSM = new DefaultComboBoxModel (semester);
    DefaultComboBoxModel<Student> comboModelMhs = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Course> comboModelCourse = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<lecture> ComboBoxModelLecturer = new DefaultComboBoxModel<>();
    Student selecttedStudent;
    Course selecteCourse;
    KRS krs;
    lecture selecLecture;
    /**
     * Creates new From InputNilai
     */
    public inputnilai (){
    initComponents();
    listMahasiswa.add(new Student("199000299","melva","018", "Ilmu Komputer"));
    listMahasiswa.add(new Student("198003272","winda","044","Ilmu Komputer"));
    listMahasiswa.add(new Student("19769046","eli","041", "Ilmu Komputer"));
    listMataKuliah.add(new Course("010", "OOP", 3, 2));
    listMataKuliah.add(new Course("011", "English", 3, 2));
    listMataKuliah.add(new Course("012", "Web", 3, 2));
    listMataKuliah.add(new Course("013", "Mobile", 3, 2));
    listLecture.add(new lecture("098", "Agus", "098", "890"));
    for (lecture item: listLecture){
    ComboBoxModelLecturer.addElement (item);
    }
    for (Student student : listMahasiswa) {
    comboModelMhs.addElement(student);
    }
    for (Course course : listMataKuliah) {
    comboModelCourse.addElement (course);
    }
    }
//        public static void main(String[] args) {
//            java.awt.EventQueue.invokeLater (()-> new inputnilai().setVisible(true));
//        }
//    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBoxMataKuliah = new javax.swing.JComboBox<>();
        jLabelKodeSks = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelHuruf = new javax.swing.JLabel();
        jComboBoxSemester = new javax.swing.JComboBox<>();
        jComboBoxDosen = new javax.swing.JComboBox<>();
        jTextFieldSIKAP = new javax.swing.JTextField();
        jTextFieldUTS = new javax.swing.JTextField();
        jTextFieldUAS = new javax.swing.JTextField();
        jButtonADD = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxNama = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabelNimProdi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIsi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxMataKuliah.setModel(comboModelCourse);
        jComboBoxMataKuliah.addActionListener(this::jComboBoxMataKuliahActionPerformed);

        jLabelKodeSks.setText("kode & SKS");

        jLabel9.setText("Nilai");

        jLabel10.setText("Pengampu");

        jLabel11.setText("Semester");

        jLabel12.setText("nilai Huruf");

        jLabelHuruf.setText("Nilai Huruf");

        jComboBoxSemester.setModel(comboModelSM);
        jComboBoxSemester.addActionListener(this::jComboBoxSemesterActionPerformed);

        jComboBoxDosen.setModel(ComboBoxModelLecturer);
        jComboBoxDosen.addActionListener(this::jComboBoxDosenActionPerformed);

        jTextFieldSIKAP.setText("0");
        jTextFieldSIKAP.addActionListener(this::jTextFieldSIKAPActionPerformed);

        jTextFieldUTS.setText("0");
        jTextFieldUTS.addActionListener(this::jTextFieldUTSActionPerformed);

        jTextFieldUAS.setText("0");
        jTextFieldUAS.addActionListener(this::jTextFieldUASActionPerformed);

        jButtonADD.setText("Add");
        jButtonADD.addActionListener(this::jButtonADDActionPerformed);

        jLabel8.setText("From Input Nilai");

        jLabel13.setText("Matakuliah");

        jLabel14.setText("Identitas Matakuliah");

        jLabel2.setText("identitas mahasiswa");

        jLabel3.setText("nama");

        jComboBoxNama.setModel(comboModelMhs);
        jComboBoxNama.addActionListener(this::jComboBoxNamaActionPerformed);

        jLabel4.setText("NIM&prodi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNimProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelNimProdi))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTableIsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "NAMA", "Matakuliah", "SKS", "Nilai", "Dosen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableIsi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonADD))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSemester, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDosen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelKodeSks, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMataKuliah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabelHuruf))
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                                        .addGap(62, 62, 62))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldSIKAP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(140, 140, 140))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelKodeSks)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSIKAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHuruf)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButtonADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNamaActionPerformed
        // TODO add your handling code here:
        this.selecttedStudent = (Student) jComboBoxNama.getSelectedItem();
        if (selecttedStudent != null){
            jLabelNimProdi.setText(selecttedStudent.getNim()+ " | Prodi:" + selecttedStudent.getstudyProgram());
        }         
    }//GEN-LAST:event_jComboBoxNamaActionPerformed

    private void jComboBoxMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMataKuliahActionPerformed
        // TODO add your handling code here:
        this.selecteCourse = (Course) jComboBoxMataKuliah.getSelectedItem();
        if (selecteCourse != null){
        jLabelKodeSks.setText(selecteCourse.getCode()+ " | SKS:  "+ selecteCourse.getSKS());
        }
    }//GEN-LAST:event_jComboBoxMataKuliahActionPerformed

    private void jTextFieldSIKAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSIKAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSIKAPActionPerformed

    private void jTextFieldUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUTSActionPerformed

    private void jTextFieldUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUASActionPerformed

    private void jComboBoxSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSemesterActionPerformed
        // TODO add your handling code here:
        setKRS();
        jLabelHuruf.setText(this.krs.getGrade());
    }//GEN-LAST:event_jComboBoxSemesterActionPerformed

    private void jComboBoxDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDosenActionPerformed
        // TODO add your handling code here:
        this.selecLecture = (lecture) jComboBoxDosen.getSelectedItem();
    }//GEN-LAST:event_jComboBoxDosenActionPerformed

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
        // TODO add your handling code here:
        selecttedStudent.addKRS(krs);
        Object[] rowData = {selecttedStudent.getNim(),selecttedStudent.getName(),krs.getCourse().getCourseName(),krs.getCourse().getSKS(),krs.getGrade(),krs.getLecturer().getName()};
        DefaultTableModel model = (DefaultTableModel) jTableIsi.getModel();
        model.addRow(rowData);
    }//GEN-LAST:event_jButtonADDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new inputnilai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADD;
    private javax.swing.JComboBox<lecture> jComboBoxDosen;
    private javax.swing.JComboBox<Course> jComboBoxMataKuliah;
    private javax.swing.JComboBox<Student> jComboBoxNama;
    private javax.swing.JComboBox<String> jComboBoxSemester;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHuruf;
    private javax.swing.JLabel jLabelKodeSks;
    private javax.swing.JLabel jLabelNimProdi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableIsi;
    private javax.swing.JTextField jTextFieldSIKAP;
    private javax.swing.JTextField jTextFieldUAS;
    private javax.swing.JTextField jTextFieldUTS;
    // End of variables declaration//GEN-END:variables

       
 private void setKRS() {
        int uas = Integer.parseInt(jTextFieldUAS.getText());
       int uts = Integer.parseInt(jTextFieldUTS.getText());
        int tugas = Integer.parseInt(jTextFieldSIKAP.getText());
        double rataRata = (uas + uts + tugas) / 3.0;
        this.krs = new KRS (selecteCourse, rataRata);
        this.krs.setLecturer(selecLecture);
        this.krs.setSemester(
    Integer.parseInt(jComboBoxSemester.getSelectedItem().toString())
);
        
    }
    
    }